create table employee (
                          id bigint generated by default as identity primary key,
                          emp_name varchar(255)
);

create table phone (
                       id bigint generated by default as identity primary key,
                       phone_type varchar(255),
                       phone_number varchar(255),
                       employee_id bigint,
                       constraint fk_phone_employee foreign key (employee_id) references employee(id)
);

create table address (
                         id bigint generated by default as identity primary key,
                         city varchar(255),
                         address_line1 varchar(255),
                         employee_id bigint,
                         constraint fk_address_employee foreign key (employee_id) references employee(id)
);