create table employee (id bigint generated by default as identity (start with 1), emp_name varchar(255), primary key (id));
create table phone (id bigint generated by default as identity (start with 1), phone_type varchar(20), phone_number varchar(20), employee_id bigint, primary key (id));
-- create table phone (id bigint generated by default as identity (start with 1), phone_type varchar(20), phone_number varchar(20), phone_order integer, employee_id bigint, primary key (id));
create table address(id bigint generated by default as identity (start with 1), city varchar(255), address_line1 varchar(255), employee_id bigint, primary key (id));
-- create table address(id bigint generated by default as identity (start with 1), city varchar(255), address_line1 varchar(255), address_order integer, employee_id bigint, primary key (id));

alter table phone add constraint fk_phone_employee foreign key (employee_id) references employee;
alter table address add constraint fk_address_employee foreign key (employee_id)  references employee;

insert into employee (id, emp_name) values (1, 'John Doe');
insert into employee (id, emp_name) values (2, 'Jane Poe');
insert into phone (id, phone_type, phone_number, employee_id) values (1, 'home', '111111', 1);
insert into phone (id, phone_type, phone_number, employee_id) values (2, 'office', '222222', 1);
insert into phone (id, phone_type, phone_number, employee_id) values (3, 'home', '333333', 2);
insert into phone (id, phone_type, phone_number, employee_id) values (4, 'office', '444444', 2);
-- insert into phone (id, phone_type, phone_number, phone_order, employee_id) values (1, 'home', '111111', 0, 1);
-- insert into phone (id, phone_type, phone_number, phone_order, employee_id) values (2, 'office', '222222', 1, 1);
-- insert into phone (id, phone_type, phone_number, phone_order, employee_id) values (3, 'home', '333333', 0, 2);
-- insert into phone (id, phone_type, phone_number, phone_order, employee_id) values (4, 'office', '444444', 1, 2);
insert into address (id, city, address_line1, employee_id) values (1, 'Budapest', 'Arany János u. 1.', 1);
insert into address (id, city, address_line1, employee_id) values (2, 'Békéscsaba', 'Jókai u. 1.', 1);
-- insert into address (id, city, address_line1, address_order, employee_id) values (1, 'Budapest', 'Arany János u. 1.', 0, 1);
-- insert into address (id, city, address_line1, address_order, employee_id) values (2, 'Békéscsaba', 'Jókai u. 1.', 1, 1);
